export const GET_NOTES = "GET_NOTES";
export const LOADING_START = "LOADING_START";
export const GET_NOTE_BY_ID = "GET_NOTE_BY_ID";
export const NOTES_FAILED = "NOTES_FAILED";
export const ADD_NOTE = "ADD_NOTE";
export const EDIT_NOTE = "EDIT_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";

export const AUTHENTICATION_START = "AUTHENTICATION_START";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const AUTHENTICATION_LOGOUT = "AUTHENTICATION_LOGOUT";